### ISSUE TITLE
[Feature suggestion] add `dev_dir` option similar to rocks-config's `plugins_dir`

### ISSUE THREAD

**Issue by NStefan002** [nvim-neorocks/rocks-dev.nvim#14]
It would be nice to have something like this in rocks.toml:
```toml
# ...

[dev]
dev_dir = "~/projects/"

# ...

"some_plugin" = { dev = true } # rocks-dev will try to find "some_plugin" in dev_dir directory
"some_other_plugin" = { dir = "~/path/to/plugin" } # rocks-dev will ignore dev_dir if dir is specified
```

I can try to implement this and open a PR if you like.
